### ISSUE TITLE
Sort ExerciseList to display for GUI

### ISSUE THREAD

**Issue by Yonggiee** [AY1920S2-CS2103T-F11-2/main#103]

**Comment by AaronCQL** [comment]
Proposed idea: use JavaFX's `TableView` to sort the rows instead.

**Comment by AaronCQL** [comment]
A custom insertion sort has been written in [`UniqueExerciseList`](https://github.com/AY1920S2-CS2103T-F11-2/main/blob/master/src/main/java/seedu/address/model/exercise/UniqueExerciseList.java), under the `addToSorted` method. This method will do a single pass of the internal list to insert the element at the correct position. This assumes that the internal list is initially sorted (which it should be, since reading from storage will do an initial sort on it).

This custom insertion sort **will guarantee an O(n) time complexity** to insert the element correctly. This is as efficient as it gets as any insertion will already incur an O(n) time complexity to first check if the internal list contains the exercise to be added.

**Comment by Yonggiee** [comment]
R u writing for me ;)

**Comment by AaronCQL** [comment]
> R u writing for me ;)

Of course

**Comment by Yonggiee** [comment]
copied ;)
